name: metadata-bilateral-exchange

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check Contract Integrity
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smart-contract
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt

      - name: Cargo Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path=./smart-contract/Cargo.toml -- --check 

      - name: Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features=enable-test-utils
  