name: metadata-bilateral-exchange

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        working-directory: ./smart-contract

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
        working-directory: ./smart-contract

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features=enable-test-utils
        working-directory: ./smart-contract
