name: Build Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-contract:
    name: Check Contract Integrity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt

      - name: Cargo Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path=./smart-contract/Cargo.toml -- --check 

      - name: Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=./smart-contract/Cargo.toml

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=./smart-contract/Cargo.toml --verbose --features=enable-test-utils

  check-client:
    name: Check Kotlin Client Integrity
    runs-on: ubuntu-latest
    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Build Project
        run: ./kotlin-client/gradlew clean build --refresh-dependencies --parallel --project-dir ./kotlin-client
  